@startuml use-case
'https://plantuml.com/use-case-diagram

Database database

skinparam actorStyle awesome
actor User #green
User--> (Home Page)
(Home Page)-->(About Us Page)
(About Us Page)-->(Info about group)
(Home Page)-->(Login)
(Login) --> (user/password incorrect)
(user/password incorrect)--> (Login)
(Login) --> (User/password correct)
(User/password correct)-->(Database Viewer)
(Database Viewer)-->(Choose element from dropdown list)
(Choose element from dropdown list)-->(WebApp)
(WebApp)----->(Server):WebApp send queries to the Database
(Server)--->database:Server receives queries from Website and sends it to the Database!
database-->(Server):Database send the filtered information back to server
(Server)-->(WebApp):Send the filtered information to WebApp.
(WebApp)--->(Display info): Display required information





note right of database
receives the enquiries, apply the desired filters
and sends back the desired information!
end note


@enduml
