@startuml
'https://plantuml.com/use-case-diagram



User-->(Login)
(Login) --> (Website)
(Website)-->(Menu)
(Menu)-->(Choose element)
(Choose element)-->(Website)
(Website)<----->[Server]
[Server]<--->[Database]
(Website)--->(Display info)

note right of (Login)
If credentials are correct,
it goes to next step
end note
note right of (Website) : User visits the page
note left of (Website)
Web requests Database
for the right info
end note
note right of [Server]
Server receives enquiries
from (Website) and sends it to the [Database]
end note
note right of [Database]
receives the enquiries, apply the desired filters
and sends back the desired information
end note


@enduml